name: Build
on:
  push:
    branches: [main]
    tags: ['v*']
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-libusb
            mingw-w64-x86_64-pkg-config
      - name: Build
        shell: msys2 {0}
        env:
          USE_STATIC_LIBS: "1"
        run: make release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lm4flash
          path: lm4flash.exe
          if-no-files-found: error
  upload-release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: lm4flash
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh -R ${{ github.repository }} release create ${{ github.ref_name }} lm4flash.exe
